### ISSUE TITLE
Node 20 is now deprecated

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle-build-action#1046]
Hey @bigdaz, would it be possible to release v2 version with Node 20?

Right now we have to choose between using beta action or using an unsupported Node.

**Comment by bigdaz** [comment]
Changing to run with Node 20 is a breaking change, and so we won't update 2.x to use Node 20.
You can expect to see a `v3.0.0` release that supports Node 20 in the next couple of weeks.

**Comment by bigdaz** [comment]
This is already fixed on the `main` branch.

**Comment by TWiStErRob** [comment]
Makes sense, thanks!
