### ISSUE TITLE
Question: Why should I use this action instead of calling gradle in my own workflow?

### ISSUE THREAD

**Issue by martinda** [gradle/gradle-build-action#110]
Why not call the gradle wrapper directly from my own workflow file? What are the benefits of using this action? Thanks in advance.

**Comment by martinda** [comment]
Another question: Does this action validate the gradle-wrapper.jar like https://github.com/marketplace/actions/gradle-wrapper-validation does?

**Comment by bigdaz** [comment]
> Why not call the gradle wrapper directly from my own workflow file? What are the benefits of using this action? Thanks in advance.

The primary benefits:
1. [Run the build with different versions of Gradle](https://github.com/gradle/gradle-build-action#download-install-and-use-a-specific-gradle-version). These distributions are downloaded and cached. (Not really a benefit if you're executing the Gradle wrapper only)
2. More sophisticated caching of Gradle User Home between invocations, compared to `setup-java` with `cache: gradle` and most pipelines using `actions/cache`.  There are [some details in the `README`](https://github.com/gradle/gradle-build-action#caching), and I plan on documenting this more in the lead up to a `v2.0` release.
3. [Automatic capture of build scan links](https://github.com/gradle/gradle-build-action#build-scans) from the build, making these easier to locate for workflow run.

> Does this action validate the gradle-wrapper.jar like https://github.com/marketplace/actions/gradle-wrapper-validation does?

No it does not.

**Comment by bigdaz** [comment]
I've added https://github.com/gradle/gradle-build-action/blob/main/README.md#why-is-this-better-than-running-gradle-directly to answer this question in the future :).

I'll close this issue now. Feel free to add comments or open another issue with more questions.
