### ISSUE TITLE
Make Gradle build output available to subsequent actions

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#112]
There are circumstances where a workflow needs to make decisions based on the output of a Gradle invocation. 
One example is running `gradle tasks` to determine if a particular tasks is available before trying to run that task. If the build output was available for processing, this would be possible.

The simple option is to make the build output available as an action output. If this proves too expensive then we could write output to file for later use.

**Comment by drmaciej** [comment]
I ended up here trying to implement an identical thing - running `tasks` to see if a task is available, then running it. I've started with a `tasks | grep` and got `Task '|' not found` back :)

**Comment by bigdaz** [comment]
@drmaciej Thanks for your feedback. I'm now spiking to see how difficult it would be to allow the action to perform caching, provisioning Gradle and build-scan capture _without_ owning the actual Gradle invocation. Something more like a `setup-gradle` action that configured everything, but allowed you to use a `run` action to actually execute Gradle.

**Comment by bigdaz** [comment]
With `gradle-build-action@v2.1` it is now possible to use the action to configure Gradle and use a standard `run` action for the actual Gradle invocation. This should allow you to capture the build output, process it however you like, and make it available to subsequent actions.

**Comment by drmaciej** [comment]
nice one, thanks!
