### ISSUE TITLE
Allow Gradle daemon to continue running between build steps

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#113]
The current implementation uses the `--no-daemon` flag to avoid the need to stop daemons at the end of the job. Instead, we should run the build as configured, keeping track of invocations and running `gradle --stop` as required at the end of the job.

**Comment by bigdaz** [comment]
As of v2.1, the daemon is still disabled, but is done via `org.gradle.daemon=false` in `~/.gradle/gradle.properties`. 

This means that, pending a fix to this issue, a workflow can provide the `--daemon` command-line argument when invoking Gradle. Any job that does so will be responsible for stopping the Gradle daemon in a later Step.

**Comment by LouisCAD** [comment]
@bigdaz
> Any job that does so will be responsible for stopping the Gradle daemon in a later Step.

By finalizing with a step running `./gradlew --stop`?

**Comment by LouisCAD** [comment]
About adding the `--daemon` option. Is there a way to enable the daemon back without having to append `--daemon` to every single command? I'd be looking for an environment variable if it can override what's specified in `~./gradle/gradle.properties`.

**Comment by bigdaz** [comment]
> Is there a way to enable the daemon back without having to append --daemon to every single command? I'd be looking for an environment variable if it can override what's specified in ~/.gradle/gradle.properties.

I'm not aware of an environment variable that does this. I suppose you could write an action that changes `~/.gradle/gradle.properties` after the `gradle-build-action` runs but before any Gradle build invocation. (This assumes that you're not using `gradle-build-action` to actually execute your Gradle builds.)

Otherwise, I'm afraid that you'll need to wait until this issue is fixed.

**Comment by LouisCAD** [comment]
Thanks for the fix! Nice to have it now right be default 🙂
