### ISSUE TITLE
Passing a script to arguments

### ISSUE THREAD

**Issue by oheyadam** [gradle/gradle-build-action#117]
Can you pass a shell script to `arguments`? We have multiple workflows that pass the same arguments, and we wanted to have these arguments in one place so we can edit them only once if we need to.

Otherwise, is there a way to create one Gradle task that executes other tasks? As in create one task that executes all the tasks we'd otherwise pass to `arguments`

**Comment by bigdaz** [comment]
No, there's no way to pass a shell script to `arguments`. You could instead use a script to generate an environment variable, and then use this environment variable everywhere in `arguments`.

You can create a task that executes other tasks in gradle with `dependsOn`:

```
tasks.register('aggregateTask') {
  dependsOn ':project:task1'
  dependsOn tasks.withType(Test)
}
```

**Comment by oheyadam** [comment]
Hey @bigdaz, thanks a lot. I actually created an aggregate task, but I get Gradle warnings about this aggregate task not being cacheable because it doesn't have any outputs. I suppose it doesn't matter since the tasks it depends on are all cacheable themselves, but I'm not entirely sure? I also added `outputs.cacheIf { true }` but that didn't solve the problem

**Comment by bigdaz** [comment]
> I suppose it doesn't matter since the tasks it depends on are all cacheable themselves, but I'm not entirely sure?

Yes it's entirely normal for a task with no action (just dependencies) not to be cacheable.
