### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#118]
Is there any possibility the action starts to use semver (2.0.0-rc.3)? There are software like Renovate or dependabot which help to update automatically all dependencies and they follow semver for default rules.

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba Thanks for the suggestion. I'll leave the existing Beta/RC versions as-is, but will use `2.0.0` for the final release (which I'm planning today).

**Comment by JavierSegoviaCordoba** [comment]
Yeah, my suggestion was for future versions, there is no need to fix the previous ones :).

Thank you for accepting it 💯
