### ISSUE TITLE
Can't differentiate between multiple build scan links from single job

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle-build-action#124]
Our GitHub actions run the Gradle action multiple times in a single job, with build scan enabled.

The title is the same for each build scan link, making it guesswork as to which one I actually want to view (there are three build scan links in this example, all from the "gradle (ubuntu-latest, 11)" job). It would be great if the title could reflect the step name, which in a sane config will be unique if there are multiple gradle build action steps configured.

![image](https://user-images.githubusercontent.com/170028/143795388-0b4b34e9-3b15-4fb2-9ae4-7b76df57426f.png)

**Comment by bigdaz** [comment]
Thanks for the report @3flex . I am aware of this issue, but I haven't been able to find any way to access the Step name from inside the executing action. In fact, even the Job description (Job Name + Matrix coordinates) is not available to the action, but is somehow used as the default title.

If you are familiar with GitHub Action implementations and are aware of a way to do this, I'd love to hear about it!
