### ISSUE TITLE
Kotlin Multiplatform build times

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#125]
I think there are some elements uncached in Kotlin Multiplatform because the build time on a very simple project is being very high.

This is the project: https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp
Build time is over 20 minutes to compile: https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp/actions/runs/1520669770

Not sure if the action is adding konan directory to the cache directories or something so.

**Comment by bigdaz** [comment]
Thanks for the report. Can you please try running the build with [cache-debugging enabled](https://github.com/gradle/gradle-build-action#cache-debugging-and-analysis)? That will give an overview of what's in the Gradle User Home for this build.

**Comment by JavierSegoviaCordoba** [comment]
This run should be using it. https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp/runs/4520591847

**Comment by JavierSegoviaCordoba** [comment]
`.konan` is not inside `.gradle`, it is in the root directory. There are more dependencies, native ones are inside `.konan`, but javascript libraries were in another place (I don't remember the folder name).

Not sure if caching that directory is the responsibility of Gradle action or not, but should be great the action supports adding custom directories to the Gradle cache so related things were cached like native dependencies or pip dependencies used by Gradle plugins (Kotlin multiplatform or docs Gradle plugins for example).

**Comment by bigdaz** [comment]
Thanks for the clarification. I think at this stage it's out of scope for `gradle-build-action` to cache arbitrary state located outside of the Gradle User Home directory. 
To enable caching for the `.konan` directory you can either:
- Use `actions/cache` to configure this caching separately
- Specify the `KONAN_DATA_DIR` environment variable to ensure that the .konan directory is located inside `~/.gradle/caches`.

Perhaps it would make sense for the `kotlin-multiplatform` Gradle plugin to place the `KONAN_DATA_DIR` within Gradle User Home.
