### ISSUE TITLE
checkstyle task fails with `Could not inspect the Groovy system for ClassLoader VisitableURLClassLoader(ant-and-gradle-loader)`

### ISSUE THREAD

**Issue by DementevNikita** [gradle/gradle-build-action#126]
Hey there!

I'm trying to migrate my GitHub Actions build script from simple ./gradlew execution to the gradle-build-action. Unfortunately even simple build task fails with:

```
* What went wrong:
Execution failed for task ':odd-platform-api:checkstyleMain'.
> Could not create service of type IsolatedAntBuilder using BuildScopeServices.createIsolatedAntBuilder().
   > Could not inspect the Groovy system for ClassLoader VisitableURLClassLoader(ant-and-gradle-loader)
```

Here is the script: https://github.com/DementevNikita/odd-platform/blob/main/.github/workflows/build.yaml
Here are the execution logs: https://github.com/DementevNikita/odd-platform/runs/4422487514?check_suite_focus=true

also attaching logs in txt just in case
[1_images.txt](https://github.com/gradle/gradle-build-action/files/7655981/1_images.txt)

**Comment by bigdaz** [comment]
Thanks for the report. I suspect that this issue is unrelated to the `gradle-build-action`, but would need to verify. 
To demonstrate that this is an issue with the action, can you please check:
1. That you can run the same build locally with JDK 17
2. That the build runs successfully with JDK 17 _without_ the `gradle-build-action`. (eg use `run: ./gradlew :odd-platform-api:build -Penv=dev ...`)

**Comment by DementevNikita** [comment]
@bigdaz thanks for the reply!

1. Yep, I run the build locally with JDK 17
2. Here is the original build file from the repo I forked: https://github.com/opendatadiscovery/odd-tracing-gateway/blob/main/.github/workflows/build.yaml. Even though it's a different gradle task (it's not working using `gradle-build-action` as well, but for the different reason) which depends on :odd-platform-api:build, it uses JDK 17 and the wrapper. I will check if the exact same command works and get back to you

**Comment by bigdaz** [comment]
@DementevNikita Do you have a follow up here? I still suspect that this issue is unrelated to the `gradle-build-action`, but it would be nice to confirm this.

**Comment by bigdaz** [comment]
@DementevNikita I'm closing this issue on the assumption that it is not a problem with `gradle-build-action`. If you can help me reproduce it, I'm happy to re-open this issue.
