### ISSUE TITLE
Update v2 tag to point to 2.1.0

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle-build-action#133]
v2 tag points to 2.0.1 meaning those trying to automatically track new updates (2.1.0 in this case) will use an older version.

Apologies if this is coming soon or deliberately held back for a time after a new release - have just been lightly singed before by projects not doing this consistently.

Thanks! New release looks great.

**Comment by bigdaz** [comment]
Thanks: I updated this locally and pushed, forgetting that it required `git push --tags`. Should be fixed now.
