### ISSUE TITLE
`Error: EBUSY: resource busy or locked, unlink...`  on Windows

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#135]
Run: https://github.com/JavierSegoviaCordoba/kotlin-stdlib/actions/runs/1669595159

**Comment by bigdaz** [comment]
Thanks for the report. I suspect that the Kotlin Compiler Daemon is not stopping after the build invocation, or it is not stopping fast enough.

**Comment by bigdaz** [comment]
With 8096e65e0ac33934b80b58fe4d0de1adc7bc586b we now wait twice as long (up to 4s) for processes to release file locks before failing to delete a file. We now also log the output of `jps -lm` in this case.

I'm going to close this issue, but if you continue to see these problems with `v2.2.0` please let me know.
