### ISSUE TITLE
How to setup with actions/setup-java@v2 ?

### ISSUE THREAD

**Issue by gotson** [gradle/gradle-build-action#137]
Hello,

i found [this issue explaining](https://github.com/gradle/gradle-build-action/issues/110#issuecomment-955468931) the benefits compared to just running the gradle wrapper.

However, all the examples in the README make use of `actions/setup-java@v1`, not `v2`.

What is the recommended practice to use this action together with `actions/setup-java@v2` ?

Should i be disabling the cache ? If the cache of `actions/setup-java@v2` is enabled in `gradle` mode, will that interfere with this action ?

Thanks

**Comment by bigdaz** [comment]
Thanks for the question. I didn't realize I was still using `actions/setup-java@v1` in all of my examples.

I've updated all references to `setup-java@v2` and mentioned that `cache: gradle` should _not_ be used in combination with this action.

To answer your question specifically: the action _should_ only restore Gradle User Home in the case that the directory does not already exist. This means that if another action (like `setup-java` or `actions/cache`) has already restored Gradle User Home, caching will be disabled for this action.

**Comment by bigdaz** [comment]
Please be aware of #138, which means that my above _should_ comment is not currently true.
