### ISSUE TITLE
Feature request - env options

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-build-action#15]
We set some env options dynamically on our builds due to github not preserving them between steps, and in our case they're computed. It would be great if there was an option like `run_init` that accepted something arbitrary to run before the gradle command

**Comment by eskatos** [comment]
Hi @ZacSweers,
Is that a common practice? Could you please share some pointers showing how this would be done from a workflow point of view?

**Comment by ZacSweers** [comment]
I don't have a public example but there re some cases where we run commands with local env vars

`FOO=bar ./gradlew build`

**Comment by ZacSweers** [comment]
A better example would be env vars that gradle or other plugins (like the android plugin seek)
 https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables

We may dynamically set the JDK in a conditional way that can't be statically defined in github actions' `env` argument alone, hence wanting a script to manage it.

**Comment by eskatos** [comment]
Hi Zac,

I can see how this could be useful. Thanks for clarifying.
I don't have that immediate need so it may take a while before I implement that myself.
Happy to review a pull request though ;) 

It is somewhat related to #18 and should be made consistent form the YAML point of view.

**Comment by bigdaz** [comment]
With `gradle-build-action@v2.1` it is now possible to [use the action to configure Gradle and use a standard `run` action for the actual Gradle invocation](https://github.com/gradle/gradle-build-action/blob/main/README.md#use-the-action-to-setup-gradle). This should allow you to benefit from the caching this action provides, but retain your existing step that invokes Gradle, including any scripted setup of the environment.
