### ISSUE TITLE
Question: Run Gradle setup error after node16 update

### ISSUE THREAD

**Issue by MRFernandez9** [gradle/gradle-build-action#153]
After #144 Im getting the following error while running the GH actions:

> [Java CI with Gradle/build] ⭐  Run Setup Gradle
> INFO[0040]   ☁  git clone 'https://github.com/gradle/gradle-build-action' # ref=v2
> [Java CI with Gradle/build]   ❌  Failure - Setup Gradle
> Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16

Any idea if I can fix this on my end?

**Comment by BorzdeG** [comment]
@MRFernandez9 As a temporary solution - roll back to version 2.1.1:  `gradle/gradle-build-action@v2` > `gradle/gradle-build-action@v2.1.1`

**Comment by MRFernandez9** [comment]
Thanks @BorzdeG !

**Comment by bigdaz** [comment]
Is this from a run on a GitHub-hosted runner? If so, what is the `runs-on:` value for the Job?
My understanding was that all runners now shipped with Node 16, but I could be wrong.

**Comment by bigdaz** [comment]
Closing for now due to lack of response.

**Comment by BorzdeG** [comment]
I have an error when running locally through [act](https://github.com/nektos/act)

Docker: 20.10.12
act: 0.2.25

**Comment by bigdaz** [comment]
@BorzdeG Thanks for clarifying. I think I'll stick with `node16` in `gradle-build-action` since support in `act` is pending.
The workaround to use an earlier release of the action will need to suffice in the interim.
