### ISSUE TITLE
Warning from GH action interweaved with GE plugin output

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-build-action#168]
If the build fails, can the warning issued by the GH action be printed after the build has finished printing all its output?

**Comment by bigdaz** [comment]
The warning/notice produced containing the build scan URL is emitted from a `buildScanPublished` block added via init script: https://github.com/gradle/gradle-build-action/blob/main/src/cache-base.ts#L274-L285

For some reason the plugin is running this block in between printing [Publishing build scan...](https://github.com/gradle/gradle-build-action/runs/5294239338?check_suite_focus=true#step:3:378) and [printing the actual build scan URL](https://github.com/gradle/gradle-build-action/runs/5294239338?check_suite_focus=true#step:3:382).

I'm not sure how easy it would be to defer the output of the action message, particularly now that the `BuildListener.buildFinished` callback has been deprecated. Perhaps the GE plugin can be changed to output the build scan URL before running any `buildScanPublished` block?

**Comment by etiennestuder** [comment]
Thanks for the investigation, @bigdaz. I don't think that changing the order in the build scan plugin is likley to happen anytime soon.

One option could be that the GH action writes the URL to a file instead of printing it to the console, and the once the build has finished, reads the file and writes it to the console. WDYT?

**Comment by bigdaz** [comment]
The `gradle-build-action` doesn't always own the Gradle execution, so it's not possible to do something immediately _after_ the build execution. I can see 2 possible options:
1. See if there is a configuration-cache compatible way to add a `buildFinished` listener to the Gradle execution that would run after the `buildScanPublished` event.
2. Write build scan URLs for each Gradle execution to disk and then emit all build-scan notices in the post-action of the `gradle-build-action` step.

The second option will be more complex and I'm reluctant to add this complexity solely to make the log output a little more readable.

**Comment by etiennestuder** [comment]
I think your option #2 is what I also meant. Or maybe I misunderstood.

Agreed that it is likely not worth the effort right now. Feel free to close the issue.

**Comment by bigdaz** [comment]
To clarify the second option, it's important to remember this use case:

```
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
   
    - name: Run Gradle tests
       run: ./gradlew test
```

The 2 `run` steps don't involve the `gradle-build-action` so they can't do anything _after_ the build. But they can/do write the scan URL to a file(s). They when we persist the Gradle User Home after all steps are complete, we could also emit the build scan notices to the User Interface. These would be delayed a little, but they wouldn't interrupt the Gradle build tool output.
