### ISSUE TITLE
Default Gradle user home doesn't match Gradle behaviour when running job inside container

### ISSUE THREAD

**Issue by equeim** [gradle/gradle-build-action#207]
When job is run inside container, gradle-build-action uses `/github/home/.gradle` as Gradle user home directory, while Gradle itself uses `/root/.gradle`. This results in empty cache.

It seems that reason is that Gradle gets user home directory from `System.getProperty("user.home")` which does not respect HOME environment variable, while Node.js `os.homedir()` (which gradle-build-action uses does).

For example, in my workflow executing `echo $HOME` prints `/github/home`, but `jshell < <(echo 'System.getProperty("user.home")')` prints `/root`

**Comment by equeim** [comment]
Yep, OpenJDK and Node.js are doing opposite things:

Node.js first checks `$HOME` and then `passwd.pw_dir`: https://github.com/nodejs/node/blob/419f02ba1f00cac3c26b7f0e9a3c01624a8b87cc/deps/uv/src/unix/core.c#L1067

OpenJDK first checks `passwd.pw_dr` and then `$HOME`: https://github.com/openjdk/jdk/blob/4df67426ed02f18af0757897acb28b636a317a91/src/java.base/unix/native/libjava/java_props_md.c#L489

It seems that Node.js is correct since Linux man page says that:
>An application that wants to determine its user's home directory should inspect the value of HOME (rather than the value getpwuid(getuid())->pw_dir) since this allows the user to modify their notion of "the home directory" during a login session.

We would need to match OpenJDK behaviour, of course.

**Comment by bigdaz** [comment]
> When job is run inside container, `gradle-build-action` uses `/github/home/.gradle` as Gradle user home directory, while Gradle itself uses `/root/.gradle`. This results in empty cache.

Can you please explain how I can reproduce this? What do you mean by "run inside container"?

In most cases the action is working as expected and the Gradle user home directly populated by Gradle is the same was saved/restored by the action.

**Comment by equeim** [comment]
I'm talking about this: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer

Here is sample project: https://github.com/equeim/gradle-build-action-sample
gradle-build-action looks for Gradle user home in /github/home/.gradle, while Gradle uses /root/.gradle

**Comment by bigdaz** [comment]
Thanks for clarifying, and thanks for the sample to reproduce. 

Yes we'll want the `gradle-build-action` to use the same algorithm as Gradle to determine the Gradle User home directory.

In the meantime, you can likely workaround this issue by explicitly setting `GRADLE_USER_HOME` env var for your build.

**Comment by tbroyer** [comment]
…or passing `-Duser.home=${HOME}` in `JAVA_TOOL_OPTIONS`.
