### ISSUE TITLE
Make dependencies caching enabled by default

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-build-action#21]
#7 introduced the caching of downloaded dependencies, disabled by default

This issue is about enabling it by default.

**Comment by LouisCAD** [comment]
For reference [I asked about caching on Gradle community Slack here](https://gradle-community.slack.com/archives/CA7UM03V3/p1591642658137600), and got a reply with [this example](https://github.com/tbroyer/gradle-errorprone-plugin/blob/4a9d57f9d99fd010a5d73f088fcc5748608e2216/.github/workflows/gradle.yaml) (although bunch of boilerplate with the yaml syntax limitations).

**Comment by payne911** [comment]
Sorry for my ignorance: would this means that somehow the GitHub Action (GHA) worker machine would be able to reuse the Gradle Wrapper I re-download every time my GHA is triggered?

Or is that only for using the cache within the same run?

**Comment by eskatos** [comment]
Hi @payne911,
Yes,  downloaded and unpacked Gradle wrapper installations are cached in GitHub infrastructure, close to the CI agents, this is shared by GitHub repository so workflow executions can reuse it.

**Comment by payne911** [comment]
Pretty crazy stuff! How do they ensure a freshly started CI Cloud Worker has all that cached?

**Comment by eskatos** [comment]
@payne911 the action itself compute a cache key, query the GitHub cache service and restore cached installations as required.

**Comment by bigdaz** [comment]
Fixed in v2.0-beta.1
