### ISSUE TITLE
Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime"

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#288]
I can't reproduce it locally.

```shell
> Task :semver-core:compileTestKotlinJsIr FAILED
e: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/home/runner/.kotlin/daemon]
e: java.lang.IllegalStateException: FATAL ERROR: Could not find "org.jetbrains.kotlin:kotlinx-atomicfu-runtime" in [/home/runner/.kotlin/daemon]
```

Run: https://github.com/JavierSegoviaCordoba/semantic-versioning-kmp/runs/6636861234?check_suite_focus=true

**Comment by JavierSegoviaCordoba** [comment]
Before reporting I tried to remove those cache directories but the problem persisted.

But locally I can't reproduce it.

I tried to change the jdk distribution and I got the same issue in actions.

**Comment by bigdaz** [comment]
A few things that might help you narrow down what's causing this:
- Try building with `gradle-build-action@main` and use the [new Job Summary](https://github.com/gradle/gradle-build-action/actions/runs/2434445701#summary-6725299463) to determine which Gradle User Home cache entries are being restored (and which aren't)
- Locally, try selectively deleting the parts of Gradle User Home that are not restored (ie remove files matching `/home/runner/.gradle/caches/*/kotlin-dsl/*/*`). This will allow you to emulate locally what a partial Gradle User Home restore would do.

**Comment by bigdaz** [comment]
Oh, and check if the issue persists when you disable the Gradle User Home cache: https://github.com/gradle/gradle-build-action#caching

**Comment by JavierSegoviaCordoba** [comment]
Looks like someone has been able to reproduce locally and a fix from coroutines is coming soon.

https://github.com/Kotlin/kotlinx.coroutines/issues/3305

Really thank you for your help and sorry for this unnecessary report :/ 

Anyway I have noted the tips for future issues 😃

**Comment by bigdaz** [comment]
Glad you got it sorted out. Thanks for continuing to provide feedback!
