### ISSUE TITLE
The build scan URL isn't always extracted properly from the logs

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-build-action#30]
From this PR (https://github.com/nokeedev/gradle-native/pull/153), we can see that some of the SCAN were not published properly. I'm using [this code](https://github.com/nokeedev/gradle-native/blob/master/.github/workflows/main.yml#L101-L117) to attach the build scan URL to the commit/checks.

<img width="920" alt="Screen Shot 2020-09-15 at 4 11 11 AM" src="https://user-images.githubusercontent.com/22181740/93156960-36710700-f6d7-11ea-99dd-a67f77b46ce3.png">

I'm wondering if we could have a debug flag to try and narrow down what is happening when the action is trying to extract the build scan URL.

**Comment by eskatos** [comment]
None of the checks on this PR successfully grabbed the scan URL except for the first `assemble` job.
https://github.com/nokeedev/gradle-native/pull/153/checks#step:6:27
And from a quick look it seems to be the same on other PRs in this repository.
OS doesn't matter, neither the build outcome.
:thinking:

**Comment by lacasseio** [comment]
You are right, I was too busy to reply with some more info. Do you have an idea about adding more logs around that part to see if it's the detection of the "Publishing build scan" or the extraction that is the problem?

**Comment by lacasseio** [comment]
We could also try to just grab the last detected URL (meaning it the last line to start with http).

Another idea would be to capture the last n lines and print them at the end of the build to debug further what is happening.

**Comment by eskatos** [comment]
One alternative would be to use an init script that captures the build scan URL from the build. It would be more solid.

**Comment by lacasseio** [comment]
Probably better, to me, it just shows how we should use Gradle instead of action to automate some of this stuff. Anyhow, there was a recent change in GitHub Action where clicking on the detail of a failing job jump straight to the end of the log as well as rendering URLs in the logs as clickable. I'm preferring this from now on, so I will just close this issue.

**Comment by eskatos** [comment]
Reopening because this is a real issue with the action that I want to see fixed

**Comment by britter** [comment]
I'm seeing this issue but only on windows: https://github.com/britter/bean-validators/pull/30

I've looked into the code but I don't see anything fishy there. I also added `-Dscan.uploadInBackground=false` but that didn't fix the problem.

**Comment by lamba92** [comment]
Same here: https://github.com/JetBrains/jetbrains-gradle-plugins/actions

Each run of the test workflow publishes a lot of build scans. You can notice the flakyness right away!

**Comment by etiennestuder** [comment]
Extracting the log should happen via buildScanPublished listener rather than via log parsing.
