### ISSUE TITLE
Configuration cache accross multiple jobs

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#317]
To indicate the version of the project, I am changing a Gradle property so I can have one job using this property as empty or in another one it as `snapshot`.

This behavior locally would drop the configuration cache every time I change the property.

Configuration cache will be reused for both jobs because they are independent? Or one job will remove the configuration cache of the another and vice-versa?

**Comment by bigdaz** [comment]
Assuming the jobs have independent cache entries for the Gradle User Home cache, then they should also have independent configuration-cache entries. So you should see configuration-cache being reused for each job.

You should be able to get a better understanding of the cache entries restored/saved by looking at the new Job Summary that came in `v2.2.0`.

Can you test if this works, and provide links to the runs (if your project is public)?

**Comment by JavierSegoviaCordoba** [comment]
I will, I have to finish the fix for getting configuration cache working but in CI I am changing the version continuously in different jobs to publish snapshots, and so on. So if this works should be great 😄

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba I'm closing this issue as an answered question. Please raise a new issue if you find the action isn't functioning the way it should.
