### ISSUE TITLE
Report issue in job summary when build scan can't be published

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle-build-action#326]
At the end of [this job](https://github.com/detekt/detekt/runs/6846095626?check_suite_focus=true#step:4:396), message in the log is:

> A build scan was not published as you have not authenticated with server 'ge.detekt.dev'.

So the link the link in https://github.com/detekt/detekt/actions/runs/2481482476 doesn't work, because there's no build scan to link to, but it's unclear from the job summary what the underlying problem is unless you try clicking the link.

Perhaps splitting the table into a success/failure message, and then having another column for build scan link (or the failure message, such as in this case when the build configuration is incorrect and the build scan wasn't published) would highlight the issue more prominently.

**Comment by bigdaz** [comment]
Just proposing some visual options for feedback.

Here is the current summary:

<table>
<tr><th>Root Project</th><th>Tasks</th><th>Gradle Version</th><th>Outcome</th></tr>

<tr><td>passing-build</td><td>with-build-scan</td><td>7.4.2</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-SUCCESS-brightgreen?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>failing-build</td><td>with-build-scan</td><td>7.4.2</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-FAILED-red?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>passing-build</td><td>no-build-scan</td><td>7.4.2</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build-SUCCESS-brightgreen?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>failing-build</td><td>no-build-scan</td><td>7.4.2</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build-FAILED-red?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>passing-build</td><td>build-scan-publish-failed</td><td>7.4.2</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build-SUCCESS-brightgreen?logo=Gradle" alt="Gradle Build"></a></td></tr>

</table>

And here's a possible improvement:

<table>
<tr><th>Root Project</th><th>Tasks</th><th>Gradle Version</th><th>Outcome</th><th>Build Scan™</th></tr>

<tr><td>passing-build</td><td>with-build-scan</td><td>7.4.2</td><td>:white_check_mark:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-brightgreen?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>failing-build</td><td>with-build-scan</td><td>7.4.2</td><td>:x:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-red?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>passing-build</td><td>no-build-scan</td><td>7.4.2</td><td>:white_check_mark:</td><td></td></tr>

<tr><td>failing-build</td><td>no-build-scan</td><td>7.4.2</td><td>:x:</td><td></td></tr>

<tr><td>passing-build</td><td>build-scan-publish-failed</td><td>7.4.2</td><td>:white_check_mark:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISH_FAILED-red?logo=Gradle" alt="Gradle Build"></a></td></tr>

</table>

And here's a possible improvement:

<table>
<tr><th>Root Project</th><th>Tasks</th><th>Gradle Version</th><th>Outcome</th><th>Build Scan™</th></tr>

<tr><td>passing-build</td><td>with-build-scan</td><td>7.4.2</td><td>:white_check_mark:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-%2306A0CE?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>failing-build</td><td>with-build-scan</td><td>7.4.2</td><td>:x:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-%2306A0CE?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>passing-build</td><td>no-build-scan</td><td>7.4.2</td><td>:white_check_mark:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-NOT_PUBLISHED-lightgrey?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>failing-build</td><td>no-build-scan</td><td>7.4.2</td><td>:x:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-NOT_PUBLISHED-lightgrey?logo=Gradle" alt="Gradle Build"></a></td></tr>

<tr><td>passing-build</td><td>build-scan-publish-failed</td><td>7.4.2</td><td>:white_check_mark:</td><td><a href="https://gradle.com/s/uohnsyk3phclg" rel="nofollow"><img src="https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISH_FAILED-red?logo=Gradle" alt="Gradle Build"></a></td></tr>

</table>

Note that in the case where none of the builds generate a build scan, we could potentially remove the "Build Scan" column altogether.

**Comment by runningcode** [comment]
I like that the third options distinguishes the color of the build scan publication from the build success failure. I think that using the same colors can be confusing. Perhaps the "publish failed" could be orange instead of red to further distinguish it?

Other than that, my preference is for the third option.

**Comment by clayburn** [comment]
I also like the third option.

Question: What will the badge link to in the "Not Published" and "Publish Failed" cases?

**Comment by bigdaz** [comment]
> What will the badge link to in the "Not Published" and "Publish Failed" cases?

@clayburn I was thinking the "Not Published" and "Publish Failed" badges could link to appropriate documentation.

**Comment by alextu** [comment]
A bit like @runningcode said, I'd say a mix of 2nd and 3rd option ie regarding the build scan column:
- "published" Blue badge when build scan is published, whether build is failing or not
- "publish failed" Gray badge when build scan publication failed
- No badge when build scan is not published (or if we want to have a badge, the "not published" Gray badge)

**Comment by bigdaz** [comment]
Thanks all for the feedback. This is what we have now, with colours and links improved: https://github.com/gradle/gradle-build-action/actions/runs/2524639182#summary-6956411171

I'm happy to do another round of polishing, but I plan to release this as `v2.2.1` pretty soon.

**Comment by 3flex** [comment]
I think that looks great, thank you for taking the feedback on board!
