### ISSUE TITLE
Action should not stop gradle deamons started by other runners on a shared host

### ISSUE THREAD

**Issue by milis92** [gradle/gradle-build-action#341]
Stoping Gradle daemons on self-hosted non-ephermal runner is currently canceling Gradle tasks that run in other jobs or workflows even. 

This is caused by the post-action step that's stoping all running daemons. 
https://github.com/gradle/gradle-build-action/blob/7f46dbd76f57c52a39d6ae9582828937129d0a3a/src/setup-gradle.ts#L103

**Comment by i-walker** [comment]
We've experienced this issue with 2.2.1 in several PR's with similar stack-traces like this one https://github.com/arrow-kt/arrow/runs/7498667115?check_suite_focus=true, where the Deamon is cancelled without the task being finished

**Comment by bigdaz** [comment]
@i-walker That appears to be an unrelated failure. This issue is about the daemon being stopped _after_ the build completes, whereas your issue is that the daemon is stopping/crashing _during_ the build.

See https://github.com/gradle/gradle/issues/19750 for a possible cause of this issue.
