### ISSUE TITLE
Question: what is the cache-read-only property

### ISSUE THREAD

**Issue by pablobaldez** [gradle/gradle-build-action#353]
I would like to know what is the `cache-read-only` and what impact it has on the project if I change it to true or false.

To give more context, In my project, the main branch is called `main`, but we used to open PR for that branch once every two weeks.
We also have the `develop` branch, which receives PRs daily (sometimes more than 10 PRs).

Which impact would I have if I set true or false to these two branches?

**Comment by nuhkoca** [comment]
@pablobaldez by default `cache-read-only` is only set `false` for default branches(in your case it should be `development`) and only default branch can write or modify the cache so other branches can only read the cache but can't write in respect to accommodating the cache size([10GB](https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/#:~:text=GitHub%20Actions%3A%20Cache%20size%20is%20now%20increased%20to%2010GB%20per%20repository,-actions&text=You%20can%20now%20enjoy%20a,repository%20has%20doubled%20to%2010GB.)) that Github grants per repository. If you set `cache-read-only` to `false`, both you'll probably often have cache misses and go over the limit easily. If you exceed the limit, don't forget that Github evicts caches.
