### ISSUE TITLE
Is it possible to include a different path for cache?

### ISSUE THREAD

**Issue by nuhkoca** [gradle/gradle-build-action#354]
Hello,

Apart from the Gradle cache, I also need to cache Sonar(test coverage) packages. Is it possible to include different path to the Gradle cache or should I use [action/cache](https://github.com/actions/cache) along with the build-action?

Sample Sonar workflow for Gradle: https://github.com/SonarSource/sonarcloud-github-action-samples/blob/2e0617f75dffbcdd03777c8162ecb8d7b43631d2/.github/workflows/build-workflow.yml#L33

**Comment by bigdaz** [comment]
At this stage, the `gradle-build-action` can only be configured to save/restore directories within the Gradle User Home directory. For directories outside of this, you'll need to configure `actions/cache` to do so.

**Comment by nuhkoca** [comment]
Thanks!
