### ISSUE TITLE
Gradle Clear Cache API is ready, what is your plan about it?

### ISSUE THREAD

**Issue by nuhkoca** [gradle/gradle-build-action#358]
As pointed out in [this](https://github.com/actions/cache/issues/2#issuecomment-1167303737) issue, [Clear Cache API](https://docs.github.com/en/rest/actions/cache) is available for deleting stale caches. Would love to see it integrated with your action. What do you think?

**Comment by bigdaz** [comment]
Thanks for pointing this out. How would you like to see the Clear Cache API integrated?

We have an existing issue (#115) for dealing with corrupted cache entries. Unfortunately in most cases there's no way for the action to automatically detect a bad cache entry vs a real build failure, so it would require the user to specify that a particular entry should be deleted. The `gradle-build-action` already makes it easy to determine the cache keys involved in a build, so a user could use this new API (or the upcoming user interface) to delete these.

Two things I think we could do better without the user manually telling us which keys to delete:
1. When running with `cache-write-only`, we could automatically delete any existing cache entries. This should have the effect of overwriting existing cache entries with the same key
2. If a cache entry is obviously corrupted (ie cannot be restored) we could delete it.

In addition, there may be ways we can use other parts of the new Cache API to report on cache usage.

**Comment by bigdaz** [comment]
The issue #370 is specifically for an enhancement using the Cache API. Closing this question
