### ISSUE TITLE
Stop fetching caches if it takes a lot of time

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#369]
GitHub Actions Cache can have issues where it takes almost forever to download them.

I think if after some time, the fetching is still running, Gradle should start to run even without reusing caches and stop trying to finish fetching caches. The previous cache shouldn't be discarded.

Run: https://github.com/JavierSegoviaCordoba/compose-resources-kmp/runs/7390287447

**Comment by bigdaz** [comment]
There's clearly an issue with `actions/cache` that is causing this.
It would be great if we could cancel the cache-restore on a configurable timeout, and continue with the rest of the action. However, there's no obvious way to do this with the `@actions/cache` API, so I think we'd need to implement something and ensure that we could effectively abort the cache restore (if the restore continued while Gradle was executing I can see this being problematic).

Ideally, the `@actions/cache` API would provide an options to set the overall timeout. There's [DownloadOptions.timeoutInMs](https://cs.github.com/actions/toolkit/blob/c5278cdd088a8ed6a87dbd5c80d7c1ae03beb6e5/packages/cache/src/options.ts#L46), but the default value of 30s is clearly not applying to the overall restore operation. I suspect this setting is the timeout for each 4Mb block.

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba I've spiked a solution to this issue in [this commit](https://github.com/gradle/gradle-build-action/commit/49c70a2943fa78c83dcea8ce9aa2130e0dae521d). The timeout is currently not configurable and is hard-coded to 2 minutes.

I haven't tested this extensively, but it would be great if you could test it out with your project. In case of a cache restore timeout you'll see an extra warning in the GitHub Actions console as well as in the caching summary rendered in the Job Summary window.

To test this out, simply reference the (unreleased) version as: `gradle/gradle-build-action@dd/cache-timeout`.

**Comment by JavierSegoviaCordoba** [comment]
@bigdaz the problem about testing this is not depending on me, it is more about the state of GitHub actions cache. 

Maybe I can see this issue multiple times on the same day that I can't see it for months, so I can put that commit but not being able to check if it works in an undetermined time.

**Comment by bigdaz** [comment]
Understood. I'll do some local testing with a shorter timeout value, but I'm really interested in how it copes with the real-world case of a cache-restore that hangs.

If you are able to switch to that branch version I'd appreciate it. I'll keep it rebased on the latest patch release of the action.

**Comment by trask** [comment]
@bigdaz I was able to still get the issue using `gradle/gradle-build-action@dd/cache-timeout`, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/7402392291?check_suite_focus=true

**Comment by bigdaz** [comment]
This issue has been reported as fixed in the `@actions/cache` library `v3.0.3`: https://github.com/actions/cache/issues/810.
The timeout currently defaults to 1hr, but I will endeavour to configure a shorter timeout.

**Comment by JavierSegoviaCordoba** [comment]
Yeah I read it and I thought that 1h timeout has no sense as default value...

**Comment by kotewar** [comment]
Hi @bigdaz, @JavierSegoviaCordoba 👋🏽 

I am from the `@actions/cache` team and we are working on giving user more control on the timeout part where you could configure the timeout in the action and not wait for an hour. The 1 hour timeout was introduced as we hadn't heard back from the [Azure team](https://github.com/Azure/azure-sdk-for-js/issues/22321) on the SDK changes that were required for fixing the problem.

**Comment by JavierSegoviaCordoba** [comment]
@kotewar thank you for the explanation 🙂

**Comment by bigdaz** [comment]
Hi @kotewar @JavierSegoviaCordoba : From my understanding the timeout configuration is already available in the `@actions/cache` _library_, as opposed to the _action_.  Here is where the `gradle-build-action` is overriding the default 1hr timeout with a configurable timeout: https://github.com/gradle/gradle-build-action/blob/8f9b7c7d7f3af702061727e299c84f445031ab56/src/cache-utils.ts#L156-L158
