### ISSUE TITLE
Publish build scan URL as a GitHub Action annotation

### ISSUE THREAD

**Issue by lamba92** [gradle/gradle-build-action#37]
A boolean parameter that publishes the build scan in the Action run would be perfect.

**Comment by bigdaz** [comment]
@lamba92 I'm just cleaning up some GH issues on this repo. Can you please clarify what you mean by "a boolean parameter that publishes the build scan in the Action run"?

I presume you mean something different from the built-in build scan support: https://github.com/gradle/gradle-build-action#build-scans

**Comment by lamba92** [comment]
I meant to publish the build scan as annotation in the workflow recap page like [here](https://github.com/JetBrains/jetbrains-gradle-plugins/actions/runs/1139049411) (code to do it available [here](https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/.github/workflows/test.yml#L31-L33))

**Comment by bigdaz** [comment]
`@actions/core v1.5.0` has added a new "notice" annotation, which is better than adding the build scan URL as a warning. That removes my initial hesitation to add this.

**Comment by bigdaz** [comment]
Fixed in v2.0-beta.1
