### ISSUE TITLE
Self-hosted runner without `unzip` installed can results in unhandled "Destination file path already exists" error

### ISSUE THREAD

**Issue by bissquit** [gradle/gradle-build-action#376]
### Description

Action fails with `Destination file path already exists` error if archive with appropriate Gradle version already exists.

### Expected behavior

Action tries to remove or reuse archive without downloading it again.

### How to reproduce

1. Run workflow on self-hosted runner without `unzip` util installed. Workflow fails;
2. Install unzip and run workflow again. Action tries to download Gradle archive again but fails because archive was downloaded at the previous step but not unarchived

**Comment by bigdaz** [comment]
Thanks for the report. Any chance you could contribute a PR for the fix?
I don't have any access to self-hosted runners to test things on.

It looks like you'd need to add a file existence check in here: https://github.com/gradle/gradle-build-action/blob/5c54c528391d07343539f7d665a2af08c9bfd64f/src/provision.ts#L135

**Comment by bigdaz** [comment]
Self hosted runners require 'unzip'.
