### ISSUE TITLE
Remove unused files from Gradle User Home before saving to Actions cache

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#406]
The Gradle User Home directory is not cleaned up in an efficient manner by Gradle, and this action doesn't do anything special to cleanup unused files in the Gradle User Home before saving it to the GitHub Actions cache. As such, no-longer-used wrapper distributions, dependencies and local cache entries will remain in Gradle User Home, causing the GitHub Actions cache entries to grow over time.

Pending a fix in Gradle itself, the action should attempt to limit the growth of the Gradle User Home over time, by removing files that were not used in the current workflow invocation.

**Comment by bigdaz** [comment]
Experimental support for Gradle User Home cleanup has been released in `v2.3.0-beta.1`. Please try this version (with cache-cleanup enabled) and let us know how it works for you.

```
- uses: gradle/gradle-build-action@v2.3.0-beta.1
  with:
    gradle-home-cache-cleanup: true
```

**Comment by sschuberth** [comment]
@bigdaz is there also a way to influence the age of cache entries to be retained? We currently do [this](https://github.com/oss-review-toolkit/ort/blob/438f3c1910a3ae92a89579e974c36bb5f818d1f3/settings.gradle.kts#L164-L170) as a work-around:

```
val buildCacheRetentionDays: String by settings

buildCache {
    local {
        removeUnusedEntriesAfterDays = buildCacheRetentionDays.toInt()
    }
}
```

**Comment by sschuberth** [comment]
> @bigdaz is there also a way to influence the age of cache entries to be retained?

I guess this could be seen as being a part of https://github.com/gradle/gradle-build-action/issues/603.

**Comment by bigdaz** [comment]
> @bigdaz is there also a way to influence the age of cache entries to be retained?

@sschuberth Can you explain why you'd want to do that? The present functionality should remove all cache entries that weren't directly used in the current workflow. This should ensure that the local build cache that is saved/restored doesn't contain any stale entries.

**Comment by sschuberth** [comment]
I'm trying to limit the cache size by pruning entries for builds that happened in CI several days ago, as we're constantly running out of the 10 GB GitHub action cache limit (not due to the Gradle cache alone, though). But if you're saying that the current implementation of `gradle-home-cache-cleanup: true` already does not keep (or save / restore) any cache entries from previous days / builds, I believe we're good.

**Comment by bigdaz** [comment]
> But if you're saying that the current implementation of gradle-home-cache-cleanup: true already does not keep (or save / restore) any cache entries from previous days / builds, I believe we're good.


Yes, it _should_. You can [see the implementation here](https://github.com/gradle/gradle-build-action/blob/main/src/cache-cleaner.ts), where we "age" all of the files before any Gradle executions, and then force the cache cleanup to run before saving the Gradle User Home.

This is a bit of a hack, but I've seen it working and have limited test coverage. Let me know if you experience otherwise.
