### ISSUE TITLE
Warning: Save Gradle User Home failed in 'beforeSave'

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle-build-action#408]
Seeing this warning [here](https://github.com/gradle/ge-solutions/runs/7876651688?check_suite_focus=true#step:8:17)
```
Warning: Save Gradle User Home failed in 'beforeSave': Error: ENOENT: no such file or directory, lstat '/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype'
```

**Comment by bigdaz** [comment]
Thanks @runningcode . I've managed to reproduce this error, which appears to be caused by a bug in the `@actions/globber` library (or it's call to `lstat`).  I have a fix in the works.

**Comment by bigdaz** [comment]
Fix is in. 
It appears that this came down to a corrupted Gradle User Home cache entry, which contained broken symbolic links for certain directories. With the fix, these are ignored and the newly created cache entry is no longer corrupted.
