### ISSUE TITLE
Why do the stats for cached entries always show 0?

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle-build-action#433]
This [blog article](https://blog.gradle.org/gh-actions) reminded me to ask something: Since the introduction of the action in [our project](https://github.com/oss-review-toolkit/ort), I yet have to see any PR where the statistics in the job summary show non-zero entries being restored / saved. So I fear that something with the setup might be wrong, any hints?

*Edit:* Just when digging out references for this issue, I came across [this line](https://github.com/oss-review-toolkit/ort/actions/runs/3052657272/jobs/4922293212#step:4:20) saying "Gradle User Home already exists: will not restore from cache". I guess that's related?

**Comment by sschuberth** [comment]
Ok, I guess I'm affected by https://github.com/gradle/gradle-build-action/issues/345 then. Still need to figure out where the existing Gradle User Home comes from, though.

**Comment by sschuberth** [comment]
Further guess,ing, the problem could be that we have the [setup-java](https://github.com/actions/setup-java) action's cache for dependencies downloaded by Gradle enabled. I'll give it a try disabling that. Will this action also cache dependencies artifacts?

**Comment by sschuberth** [comment]
> Will this action also cache dependencies artifacts?

Yes it [does](https://github.com/gradle/gradle-build-action#caching) 👍🏻

**Comment by bigdaz** [comment]
Thanks for the report and analysis. Yes, the "Gradle User Home already exists" is certainly the reason for no caching on your project. If the action finds an existing Gradle User Home directory then it won't attempt to overwrite/merge something saved from a previous run. This scenario should be better reported by the action: I've raised #434 for this.

If you're using a self-hosted runner that has persistent state between runs, then th Gradle User Home should be fully persisted between Jobs, and the `gradle-build-action` caching won't add much value.

But I see that you reported using the `cache: gradle` option from `setup-java`. Yep, this would cause a partial restore of the Gradle User Home (but only the dependencies in a fairly naive way). The `gradle-build-action` takes care of this for you, so you can safely remove that option from `setup-java`.

**Comment by sschuberth** [comment]
> The `gradle-build-action` takes care of this for you, so you can safely remove that option from `setup-java`.

I'm testing that now [here](https://github.com/oss-review-toolkit/ort/pull/5796) and will close this issue if that succeeds.

**Comment by bigdaz** [comment]
You may also be interested in this article that was just published: https://blog.gradle.org/gh-actions

**Comment by sschuberth** [comment]
Yes, that's what reminded me to ask this question, see the edit I had done to my first comment 😀

**Comment by sschuberth** [comment]
> I'm testing that now [here](https://github.com/oss-review-toolkit/ort/pull/5796) and will close this issue if that succeeds.

Disabling setup-java's Gradle cache indeed seems to do the trick!
