### ISSUE TITLE
[Question] Recommendation for using daemon?

### ISSUE THREAD

**Issue by kkocel** [gradle/gradle-build-action#435]
I wonder when using this action should I use daemon or should I disable it?

      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build --no-daemon

**Comment by bigdaz** [comment]
There's no reason to disable the daemon like this. Gradle will almost always start a new "single use" daemon anyway, and the `gradle-build-action` will take care of stopping the daemon at the end of your Job.
