### ISSUE TITLE
Support for Dependency submission API

### ISSUE THREAD

**Issue by osiegmar** [gradle/gradle-build-action#449]
Any plans to add support for [Dependency submission API](https://docs.github.com/en/rest/dependency-graph/dependency-submission)?

I found https://github.com/marketplace/actions/gradle-dependency-submission but I think this functionality should be available directly within gradle-build-action.

See also https://github.com/community/community/discussions/11117.

**Comment by tbroyer** [comment]
Fwiw, Jonathan Leitschuh started https://github.com/gradle/github-dependency-extractor before leaving Gradle, Inc.
I'd love it for Gradle to finish it and integrate it into gradle-build-action.

**Comment by bigdaz** [comment]
There are no current plans to support this in `gradle-build-action`. 

My understanding is that https://github.com/gradle/github-dependency-extractor has significant issues and performance overhead, and will require quite some work to finish. 

I wasn't aware of https://github.com/mikepenz/gradle-dependency-submission but it's reliance on the `dependencies` task implies that it will only capture a subset of the actual runtime project dependencies. This is possibly better than nothing, but I know that Johathan wanted his implementation to capture all development and runtime project dependencies.

**Comment by big-andy-coates** [comment]
+1 on supporting the new dependency API or _something_ that gives users Dependabot security alerts for Gradle on GitHub.

**Comment by bigdaz** [comment]
Closing as not directly related to `gradle-build-action`. However, the Gradle Build Tool team is working on plans to support the GitHub Dependency Submission API: expect to see something on the [Gradle Build Tool roadmap](https://github.com/orgs/gradle/projects/31/views/1) soon.
