### ISSUE TITLE
Is Gradle daemon needed when running a single Gradle task

### ISSUE THREAD

**Issue by Waltari10** [gradle/gradle-build-action#457]
I am using gradle/gradle-build-action@v2 to run a single Gradle task in my Github Action job. Everytime it runs the Gradle task it starts a Gradle daemon which takes about 15-20 seconds. Is this 15-20 seconds wasted since I'm only running a single job? Or are you able to cache the Gradle Daemon files somehow as well so that it makes following builds using Gradle Daemon faster?

I managed to prevent the Gradle Daemon from starting, but it's a bit hacky, so I'm wondering if the hack is needed to speed up the build process or not.

**Comment by Waltari10** [comment]
Looking at these screenshots it seems it begins to start the Gradle daemon and the next log is only 15-60 seconds later. I guess it's also possible that it's the next task taking the time if at the end of starting the daemon there is no logging and at the beginning of the next task there is no logging...

<img width="598" alt="Screenshot 2022-10-24 at 11 47 26" src="https://user-images.githubusercontent.com/8919286/197486363-604119a0-8b17-4ed9-988d-2823ac17132c.png">
<img width="659" alt="Screenshot 2022-10-24 at 11 46 35" src="https://user-images.githubusercontent.com/8919286/197486365-f314b5ba-c042-4c25-b200-0327f5d04493.png">
<img width="871" alt="Screenshot 2022-10-24 at 11 43 45" src="https://user-images.githubusercontent.com/8919286/197486369-8d6f2950-79c4-4093-a048-3da6b88973d0.png">


How does it restore the state between Github Actions Jobs when it could be starting the next job on a completely different machine?

I added caching of the ~/.gradle folder. If I restore said folder is the Daemon then able to restore state and speed up the build process even though it's ran on a different machine?

**Comment by bigdaz** [comment]
> Looking at these screenshots it seems it begins to start the Gradle daemon and the next log is only 15-60 seconds later.

It's hard to speculate on what's taking the time: there are many different possibilities. Do you consistently see a bigger gap in the logs with the daemon compared to running with `--no-daemon`?

A few things you could do to help diagnose/improve your build startup times:
- Generate a [Build Scan](https://scans.gradle.com/) that contains detailed profiling information
- Compare running the build locally with running the build on GitHub Actions
- Compare running the build locally after first removing the `<project-dir>/.gradle` directory
- Share a GitHub Actions run (if these are public)
