### ISSUE TITLE
Allow existing Gradle User Home to be overwritten with cached contents

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#480]
When self-hosted runners are used, the Gradle User Home caching is often disabled due to a pre-existing Gradle User Home directory. The following messages appear:

- In the main step: `Gradle User Home already exists: will not restore from cache.`
- In the post-action: `Cache will not be saved: not restored in main action step.`

Ideally, there would be a way for Users to opt-in to replacing any existing Gradle User Home with the contents from the cache.
We'd need to deal with any currently running Gradle Daemon processes as well.

**Comment by ZacSweers** [comment]
Big plus to this. In our use-case, we write some properties to `~/.gradle/gradle.properties` before starting the build and this behavior more or less negates the cache support of this action.
