### ISSUE TITLE
Disable generation of Job Summary

### ISSUE THREAD

**Issue by bartekpacia** [gradle/gradle-build-action#483]
I use `gradle-build-actions` in my workflow, but it's non-essential to it and I'd prefer to have it not clutter my Job Results tab.

![Screenshot 2022-10-26 at 12 45 44 AM](https://user-images.githubusercontent.com/40357511/197896150-b015cb96-f219-4f62-bca7-59b0a37d7a2b.png)

Is there a way to disable Job Results?

**Comment by bigdaz** [comment]
Yep, the action has a `generate-job-summary` parameter that allows you to disable the summary.
https://github.com/gradle/gradle-build-action/blob/main/action.yml#L56
