### ISSUE TITLE
function locateGradleAndDownloadIfRequired errors in download tool if version has been downloaded but not installed

### ISSUE THREAD

**Issue by vml-aledonne** [gradle/gradle-build-action#510]
function locateGradleAndDownloadIfRequired checks if the requested version is _installed_ but if it is not installed immediately attempts to download without checking if the requested version has been _downloaded_

If the zip file exists in gradle-installations/downloads/ , the download tool throws Error: Destination file path ... already exists

the function should check for existence of the .zip file in between checking for the installation and initiating the download.

**Comment by bigdaz** [comment]
Duplicate of #376
