### ISSUE TITLE
Don't cache child branches when nothing changed

### ISSUE THREAD

**Issue by bjoernmayer** [gradle/gradle-build-action#511]
Hi,

we allow child branches to allow writing to cache in our repository.
Doing that saves us 3 minutes of build time.

However: We are constantly approaching the total cache storage limit. Which can be okay, but isn't optimal.

I noticed that we have cache entries for branches, that do not change e.g. any dependencies.

Does it make sense to store a cache entry for a child branch, if there are no changes compared to the parent cache?

In case you can compare pre-build and post-build caches and see no difference, you don't need to write it.
Next build will use the parent cache then.

This could save some cache storage for any other branch.

**Comment by bjoernmayer** [comment]
nvm.
I went through the debug output and you are already doing that.
Still: dependencies are written, although nothing has changed.
I will look into it, and maybe create another issue. Closing this one

**Comment by bigdaz** [comment]
You can inspect the caching summary report ([example here](https://github.com/gradle/gradle-build-action/actions/runs/3527816664#summary-9653642990)) to get a good idea of what entries are being written and why.
