### ISSUE TITLE
./gradlew: Permission denied

### ISSUE THREAD

**Issue by pplmx** [gradle/gradle-build-action#517]
the demo should add
```yml
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
```

**Comment by tbroyer** [comment]
Are you developing on Windows? (and outside WSL) Because that script should already be executable for anyone on Linux or macOS.

**Comment by pplmx** [comment]
Win 11. chmod locally and recommit it, works fine now. Thanks. :)

**Comment by herberson** [comment]
Instead of a step running chmod you can use:

```
    - name: Build with Gradle Wrapper
      run: bash ./gradlew build
```
