### ISSUE TITLE
Configuration cache miss on `processResources` task of included build Gradle plugin

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-build-action#540]
I am seeing the following configuration cache miss when running with the Gradle Build Action:

`Calculating task graph as configuration cache cannot be reused because an input to task ':build-logic:reproducer-plugin:processResources' has changed.`

See [here](https://github.com/erichaagdev/configuration-cache-process-resources-reproducer/actions/runs/3725761500/jobs/6318772513#step:4:11) for an example.

I was able to consistently reproduce this issue. You can find the reproducer as well as steps to reproduce here: https://github.com/erichaagdev/configuration-cache-process-resources-reproducer

This can also be recreated locally when the `build-logic/reproducer-plugin/build` folder is removed between executions of `./gradlew build`.

Some additional information about the project:
- The project has an included build with a Gradle plugin subproject
- The Gradle plugin is applied to the root project

**Comment by sula-sa** [comment]
Seeing the same issue when using an included build with custom Gradle plugins

**Comment by bigdaz** [comment]
Closing as the `gradle-build-action` no longer saves the configuration-cache data between invocations.
