### ISSUE TITLE
Gradle setup can fail on Act when not providing gradle-version

### ISSUE THREAD

**Issue by Porkepix** [gradle/gradle-build-action#598]
First, it brings a question I'm not not sure about even after checking doc & code, is the parameter `gradle-version` supposed to be mandatory, or optional?

It turns out, as I'm understanding it that the action should setup `gradle`, however while it works flawlessly without specifying it on GitHub's runner, when using https://github.com/nektos/act with default images (that might lack some tools present by defaults on official runners) it seems to result in Gradle not being installed. And therefore have the following commands failing as Gradle seems to be missing from those images.
But this isn't failing if we specify eg. `gradle-version: current`, as here the installation happens correctly.
Is this the expected behavior? (ie. is it expected to not install gradle if we don't specify this variable?)

**Comment by bigdaz** [comment]
I believe this is a duplicate of #426: can you confirm? In particular see [this comment](https://github.com/gradle/gradle-build-action/issues/426#issuecomment-1243183814) that describes the issue in more detail.

**Comment by Porkepix** [comment]
This indeed looks like the same issue.
