### ISSUE TITLE
Build scans are not captured

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#626]
In this [run](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/actions/runs/4394281726/jobs/7695235133) it is possible to see the scan in the logs

![image](https://user-images.githubusercontent.com/7463564/224512690-0fa24992-a919-4c89-b130-b3457794911b.png)

But in the summary it is not appearing:

![image](https://user-images.githubusercontent.com/7463564/224512721-453e8e2b-d747-4c42-8631-35fb77dba5d5.png)

https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/actions/runs/4394281726#summary-11932819131

**Comment by JavierSegoviaCordoba** [comment]
Yes, it is happening on all projects on different workflows. I am using reusable workflows, not sure if that can be the problem.

I don't know what do you mean about reproducing it locally, I haven't developed any GitHub Action before 🤔

**Comment by bigdaz** [comment]
The way the action captures the build scan is via some scripts placed in the Gradle User Home `init.d` directory. If you put these in your local Gradle User Home you might be able to debug why they aren't working.

So to reproduce:
1. Copy the init scripts linked above into `~/.gradle/init.d`.
2. Export the appropriate env vars: `RUNNER_TEMP` is a directory and `GITHUB_ACTION` can be any string.
3. Run the build
4. Look for a `.build-results` directory generated in the `RUNNER_TEMP` directory.
5. If you don't see it, add some `println` statements to see where the initialization scripts are failing.

**Comment by JavierSegoviaCordoba** [comment]
There is a json file:

GRADLE_ACTION-1680031868132.json
```json
{
  "rootProjectName": "gradle-extensions-project",
  "rootProjectDir": "D:\\Repos\\gradle\\gradle-extensions",
  "requestedTasks": "assemble",
  "gradleVersion": "8.0.2",
  "gradleHomeDir": "C:\\Users\\javøie\\.gradle\\wrapper\\dists\\gradle-8.0.2-bin\\25jlreiuz6u3xu2phlpa2vv4m\\gradle-8.0.2",
  "buildFailed": false,
  "buildScanUri": "https://gradle.com/s/bai43tyy44txq",
  "buildScanFailed": false
}
```

**Comment by bigdaz** [comment]
Thanks. I think the fact that this file generates for you locally (with a `buildScanUri`) indicates something amiss in the action post-processing. I'm not actively working on this project at the moment, but will attempt to reproduce/fix this problem before the next major release.

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba I finally got around to investigating this. It turns out that the issue was due to the way we detect the `com.gradle.enterprise` plugin being applied, and the fact that you are [applying the plugin inside a `settingsEvaluated` block](https://github.com/JavierSegoviaCordoba/hubdle/blob/main/hubdle-gradle-plugin/main/kotlin/com/javiersc/hubdle/settings/HubdleSettingsPlugin.kt#L47).

While I think it's a bit odd to apply a settings plugin during `settingsEvaluated`, I've found a way to modify our init scripts so they handle this case.

Can you please try running your project with `gradle/gradle-build-action@dd/issue626` and check if build scan links are correctly captured?

**Comment by JavierSegoviaCordoba** [comment]
How should I apply it?

**Comment by bigdaz** [comment]
Apologies, I missed the hyphen from the version: you can literally reference `gradle/gradle-build-action@dd/issue-626` in your YAML file.
So replace `gradle/gradle-build-action@v2` with `gradle/gradle-build-action@dd/issue-626`.

This will cause your workflow to run with the action code in the [dd/issue-626 branch](https://github.com/gradle/gradle-build-action/tree/dd/issue-626).

**Comment by JavierSegoviaCordoba** [comment]
Sorry I was referring to gradle enterprise and how to apply it on settings plugins

**Comment by JavierSegoviaCordoba** [comment]
It works, feels free to close it now or when the change is published :)

**Comment by bigdaz** [comment]
> It works, feels free to close it now or when the change is published :)

Will do. Can you confirm that by "it works" you mean that you tried the `dd/issue-626` branch and you are now getting build scan links published?

Did you also try moving the plugin application outside of the `settingsEvaluated` block? Just curious.

**Comment by JavierSegoviaCordoba** [comment]
I moved it but I haven't tested it yet, I will share it here when the test is done!

**Comment by JavierSegoviaCordoba** [comment]
Applying the plugin as you have said works too, thank you 🙏
