### ISSUE TITLE
Failed to delete gradle-api-8.0.2.jar on Windows

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle-build-action#636]
https://github.com/Goooler/jmh-gradle-plugin/actions/runs/4469841298

```
Failed to delete C:\Users\runneradmin\.gradle\caches\8.0.2\generated-gradle-jars\gradle-api-8.0.2.jar, which will impact caching. 
It is likely locked by another process. Output of 'jps -ml':
5604 jdk.jcmd/sun.tools.jps.Jps -lm
```

```
Unhandled error in Gradle post-action - job will continue: Error: EBUSY: resource busy or locked, unlink 'C:\Users\runneradmin\.gradle\caches\8.0.2\generated-gradle-jars\gradle-api-8.0.2.jar'
```

**Comment by bigdaz** [comment]
Thanks for the report. This warning is issued when a process is left running that locks the file. In this case, I suspect the Kotlin compiler had not stopped.

Closing this issue as it's not currently repeatable or actionable. Please comment again if the issue persists.
