### ISSUE TITLE
Is there a way to disable job summary?

### ISSUE THREAD

**Issue by aruke** [gradle/gradle-build-action#645]
Job summaries with detailed explanation on cache and build scans are great, but I want to use them only when I am developing the workflow, and not much after that. 
Is there a way to disable them? I tried `rm $GITHUB_STEP_SUMMARY` but it seems the summary is generated in post action job.

**Comment by bigdaz** [comment]
Yes, you can use the `generate-job-summary` parameter that is mentioned here: https://github.com/gradle/gradle-build-action/blob/main/action.yml#L56-L59.

I've raised #646 as an issue to get this properly documented. PRs welcome.

**Comment by aruke** [comment]
Thanks @bigdaz !!
