### ISSUE TITLE
Wrong link to marketplace in About section

### ISSUE THREAD

**Issue by Undin** [gradle/gradle-build-action#66]
Currently, `About` section contains `https://github.com/marketplace/actions/gradle-command` link but it should be `https://github.com/marketplace/actions/gradle-build-action` since action was renamed recently

**Comment by bigdaz** [comment]
Thanks for the report. This is now fixed.

**Comment by Undin** [comment]
@bigdaz note, current link is `https://github.com/marketplace/actions/gradle-build` not `https://github.com/marketplace/actions/gradle-build-action`

**Comment by bigdaz** [comment]
Doh! Fixed for real now!
