### ISSUE TITLE
Parallel download and extracting

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle-build-action#677]
We use this action in the [sqldelight repo](https://github.com/cashapp/sqldelight/actions/caches) resulting in 40 cache artifacts with 15 GB in sum. Downloading and extracting these caches, roughly about 10 GB per os, is very slow and takes around 10 minutes.
I guess this is due to single-threaded logic. Would using multiple cores/threads for downloading and extracting the compressed artifacts accelerate our builds?

**Comment by bigdaz** [comment]
The action first downloads the primary entry for the Gradle User Home (with a key something like `v7-gradle|Linux|...`).
This entry contains keys for the other entries (like `dependencies-*`, `java-toolchains-*` etc). These other entries _are_ downloaded in parallel, as you can see from [this log](https://github.com/cashapp/sqldelight/actions/runs/4736919218/jobs/8409084555#step:4:20). Note that the "Received X of Y" messages are interleaved for artifacts of different sizes.

I believe the main thing slowing down your build is the need to download very large cache entries. For example, in [this build](https://github.com/cashapp/sqldelight/actions/runs/4736919218#summary-12845752477) you can see that the `dependencies-*` cache entry contains over 2.7Gb of data.

The first thing you can do is [enable cache debugging](https://github.com/gradle/gradle-build-action#cache-debugging-and-analysis): the logs will give you an idea of what files are being restored in each cache entry. It's possible that the dependencies entry contains many files that were downloaded in the past but are not required for the build invocation in question.

Once you have an understanding of the problem, you have a couple of things you can try to reduce the total volume of downloaded cache entries, as documented in [Optimizing Cache Effectiveness](https://github.com/gradle/gradle-build-action#optimizing-cache-effectiveness).
The most likely thing to help (and simplest thing to do) is to enable [Gradle User Home cleanup](https://github.com/gradle/gradle-build-action#removing-unused-files-from-gradle-user-home-before-saving-to-cache).

**Comment by hfhbd** [comment]
Thanks for your fast answer and your help. I will try to implement these optimizations.
