### ISSUE TITLE
[BUG] generate-job-summary give 502 on GitHub Enterprise 3.8.1

### ISSUE THREAD

**Issue by ycreachcadec** [gradle/gradle-build-action#687]
Hello guys,

FYI it looks like using action gradle-build-action in version >= 2 (tested in v2 and v2.4.2) broke the GUI in GitHub Enteprise in 3.8.1.
Error 502 ![image](https://user-images.githubusercontent.com/17435306/233965895-484bd90f-f39a-49d7-b55f-c7630606036c.png)

I have to sett parameter generate-job-summary to **false** to avoid this 502 error.

Note that it works well in Github Enterprise 3.7.4, in action v2 or v2.4.2

Following tests was made : 

- using gradle-build-action@1  on GitHub Enteprise in 3.8.1=> **OK**
- using gradle-build-action@v2 on GitHub Enteprise in 3.8.1 => error 502
- using gradle-build-action@v2.4.2  on GitHub Enteprise in 3.8.1 => error 502
- using gradle-build-action@v2.4.2  on GitHub Enteprise in 3.8.1 with parameter generate-job-summary: false => **OK**
- using gradle-build-action@v2 on GitHub Enteprise in 3.7.4 => **OK**
- using gradle-build-action@v2.4.2  on GitHub Enteprise in 3.7.4 => **OK**

**Comment by bigdaz** [comment]
Thanks for your report. Note that using `v2` or `v2.4.2` is effectively identical: `v2` currently points at `v2.4.2`.
The Job Summary functionality was introduced in `v2.2.0`. I don't expect any earlier versions to suffer from the problem.

Unfortunately I don't have access to a GitHub Enterprise server for testing. I looked over the GitBug Enterprise v3.8 release notes and didn't see anything suspicious.

 Are you able to provide any more details of the failure, like log messages from the server?

Without such details, it will be very difficult to fix this bug.

**Comment by bigdaz** [comment]
I'm unable to reproduce this issue. Please comment here if you can provide more information to assist me to reproduce and fix.
