### ISSUE TITLE
Add cache read timeout?

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle-build-action#705]
Would you consider adding a cache read timeout (see also https://github.com/gradle/gradle-build-action/issues/415)?

Right now a timeout is set to 10 min ([source](https://github.com/gradle/gradle-build-action/blob/eb126d771e2fad56aea2b224b1764ca712b41ce9/src/cache-utils.ts#L29)). I'm not sure whether it's global or number of minutes without receiving a packet but in all cases, 10minutes is a long time. Once the connection established and the cache starts downloading, there's a high chance the network is down if no packet is received in a few seconds.

Reclaiming that time would allow the subsequent steps to finish faster.

**Comment by bigdaz** [comment]
You can override the default cache read timeout by setting the `SEGMENT_DOWNLOAD_TIMEOUT_MINS` environment variable ([source](https://github.com/gradle/gradle-build-action/blob/eb126d771e2fad56aea2b224b1764ca712b41ce9/src/cache-utils.ts#L159-L162)). If this mechanism works for you, please let me know and we can consider reducing the default in `gradle-build-action`.

Previously, the default timeout for `actions/cache` was 60mins, and the `gradle-build-action` overrode this to 10mins (but only if the environment variable is not explicitly set). I now see that the [latest release of `actions/cache`](https://github.com/actions/cache/blob/main/RELEASES.md#331) has changed the default to 10mins, so I can probably remove this override.

**Comment by martinbonnin** [comment]
> an override the default cache read timeout by setting the SEGMENT_DOWNLOAD_TIMEOUT_MINS environment variable

Nice, thanks! Sorry I missed that! This is a global timeout for the cache entry though right? It'd be interesting to have a "read timeout" (not really sure how to name it) that triggers if no byte is received after the given timeout. There could also be a "connect timeout" for the initial byte.

The reason being that we have 40MB cache entries and 2GB cache entries (for dependencies). Using the same global timeout for both doesn't really make sense.

**Comment by bigdaz** [comment]
The `gradle-build-action` is dependent on the functionality provided by the [GitHub Actions Cache library](https://github.com/actions/toolkit/tree/main/packages/cache#cache-segment-restore-timeout), and this is the only configuration option they provide. Before this timeout was introduced, I tried to implement a caller-side timeout but wasn't very successful.

If you'd like finer-grained control over cache entry download, I suggest that you raise an issue against the [toolkit library](https://github.com/actions/toolkit), or against [`actions/cache`](https://github.com/actions/cache) which is the main GitHub Action using this library.

**Comment by martinbonnin** [comment]
Makes sense, thanks! Closing this issue.

**Comment by martinbonnin** [comment]
Follow up there: https://github.com/actions/cache/issues/1170
