### ISSUE TITLE
Support for writing log to file

### ISSUE THREAD

**Issue by cortinico** [gradle/gradle-build-action#72]
Hey all, thanks for the great GH Action.

It would be great if we could redirect the Gradle log output to file in some form.
Specifically having the log on file could be useful for parsing and for asserting that a task was effectively executed.

When not using this action it's as easy as `run: ./gradlew tasks | tee gradle.log`.
Once we switch to this action, it seems like there is no easy way to make it possible.

**Comment by bigdaz** [comment]
With `gradle-build-action@v2.1` it is now possible to use the [action to setup Gradle but use a standard `run` action for the actual Gradle invocation](https://github.com/gradle/gradle-build-action/blob/main/README.md#use-the-action-to-setup-gradle). This should allow you to capture the build output, process it however you like, and make it available to subsequent actions.
