### ISSUE TITLE
Docs: clarify usage of actions/setup-java with this action

### ISSUE THREAD

**Issue by JoshMcCullough** [gradle/gradle-build-action#725]
From the docs:

>When using gradle-build-action we recommend that you not use actions/cache or actions/setup-java@v3 to explicitly cache the Gradle User Home. Doing so may interfere with the caching provided by this action.

I believe you are saying to just not enable the caching feature of `actions/setup-java`, but surely we can still use that action to install a specific JDK. Is that correct? If so, I can provide a PR to adjust the docs.

**Comment by bigdaz** [comment]
Yes, you can still use `actions/setup-java`: what's not recommended is using the `cache: gradle` option with `setup-java` [like this](https://github.com/actions/setup-java#caching-gradle-dependencies).

I'll try to get the docs updated before the next release. A PR would be appreciated :).

**Comment by ankushg** [comment]
I believe this is also relevant: https://github.com/gradle/gradle-build-action/issues/561
