### ISSUE TITLE
Cache Gradle distributions downloaded by TestKit

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-build-action#73]
When using this action on a Gradle plugin build that runs TestKit tests against several Gradle versions, TestKit downloads the Gradle distributions to a dedicated "gradle user home".

Currently the distributions downloads happen on each job run, slowing down the feedback loop.

It would be nice to cache those distributions downloads.

**Comment by bigdaz** [comment]
@tbroyer is correct: distributions downloaded by TestKit are stored in the main Gradle User Home. One oddity is that when the main build is run with `-g /alternate/gradle/home`, this setting is ignored by TestKit which always downloads distributions to `~/.gradle`.

I've added a test that verifies that a Gradle Plugin project can run `--offline` when the Gradle User Home is restored from a previous execution. Any `TestKit` state that is not stored in the main Gradle User Home will not be cached.
