### ISSUE TITLE
Setting the `GRADLE_USER_HOME` env var prevents caching of content in the Gradle User home

### ISSUE THREAD

**Issue by chiefy** [gradle/gradle-build-action#74]
Unless I am mistaken, if you override `GRADLE_HOME` env dir to be non-standard [the caching functions won't work](https://github.com/gradle/gradle-build-action/blob/main/src/cache-wrapper.ts#L122-L123)? Might be beneficial to add a note in the docs. I was just wondering why nothing was caching for my project :) Thanks!

**Comment by bigdaz** [comment]
Thanks for the report @chiefy, you are indeed correct. I think instead of warning we should detect the `GRADLE_HOME` environment variable and change the cache paths as appropriate.

I'll push this fix into the upcoming v2 release, and could possibly backport to v1 if required.

**Comment by bigdaz** [comment]
Correction: the variable is `GRADLE_USER_HOME`
