### ISSUE TITLE
Support GitHub merge groups

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle-build-action#766]
GitHub added a new merge groups feature, which is in Beta: https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

Docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

Under the hood, GitHub creates a new branch, but this branch does not reuse the existing Gradle cache, thus resulting into longer builds.
Sample:
![image](https://github.com/gradle/gradle-build-action/assets/22521688/45b0a4fd-c19d-4814-a664-bc4d450f8b8c)

**Comment by hfhbd** [comment]
I rechecked the repo with merge-group enabled and it does work now as expected. Maybe it was a GitHub issue fixed in the mean time.

BTW I also tried the new GitHub dependency submission feature and it works really nice!

**Comment by bigdaz** [comment]
Thanks so much for rechecking, and your feedback on dependency-submission.
Please let me know if you have any issues or suggestions.
