### ISSUE TITLE
Is there a way to disable wrapper-zips?

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle-build-action#783]
There's no need to cache wrappers (in case cache space could be an issue), because the `gradlew` download is near "instant":
![image](https://github.com/gradle/gradle-build-action/assets/2906988/b650ed9a-19fc-4e82-8eac-cfb80e023d25)

Using the GHA runner caches instead of a custom cache is probably a good idea. This might not apply to all versions of the wrapper, or all GHA envs, but an option to choose which bundles to cache would be nice.

**Comment by tbroyer** [comment]
You can exclude the `wrapper` directory: https://github.com/gradle/gradle-build-action#gradle-user-home-cache-tuning

**Comment by TWiStErRob** [comment]
Ah, nice, thanks!
