### ISSUE TITLE
How do I update the cache of the snapshot version?

### ISSUE THREAD

**Issue by RinOrz** [gradle/gradle-build-action#82]
I have one like following code, but dependency doesn't seem to use the latest
```kotlin
plugins {
  id("com.meowool.gradle.toolkit") version "0.2.2-SNAPSHOT"
}

buildscript {
    // Check for updates every build
    resolutionStrategy {
      cacheChangingModulesFor(0, TimeUnit.SECONDS)
    }
}
```

**Comment by bigdaz** [comment]
I think your question is about the [Gradle Build Tool](https://github.com/gradle/gradle). If that's the case, please open an issue there. If you have a question about the `gradle-build-action` that is used to execute Gradle in a GitHub Actions workflow, please clarify your question and I'll reopen this issue.
