### ISSUE TITLE
Tag action in marketplace so users can find it for dependency reporting

### ISSUE THREAD

**Issue by big-andy-coates** [gradle/gradle-build-action#837]
When Gradle users view their dependency graph in GitHub they currently get a note at the top informing them how to "Detect additional dependencies with GitHub actions". This has a "View in Marketplace" button with the following link: https://github.com/marketplace?query=dependency+submission+gradle.

Unfortunately, this doesn't bring up this projects action, only one written by a 3rd party. 

To aid discovery of this project's action and to help Gradle users, it would be useful if this action was reported in the list.

Not sure how to achieve this without getting in touch with GitHub and getting them to change the link to https://github.com/marketplace?query=dependency+management+gradle, and then adding the "Dependency management" category to this project's action.

![image](https://github.com/gradle/gradle-build-action/assets/8012398/1eb85dc8-cedd-43cf-8bee-02ecc36c3c34)

**Comment by bigdaz** [comment]
Can you help me reproduce this message? If I start with a vanilla Gradle project, I see this message. 
<img width="912" alt="image" src="https://github.com/gradle/gradle-build-action/assets/179734/3521fe73-1c85-40b7-8ba2-c0ab972bffa2">

**Comment by big-andy-coates** [comment]
Not sure - maybe add a dependabot config file?

Similar to https://github.com/creek-service/creek-base/blob/main/.github/dependabot.yml

**Comment by bigdaz** [comment]
Thanks, I've tried that and still don't see the message. I've reached out to the GitHub team responsible to see if they can help.

**Comment by bigdaz** [comment]
By updating the "description" field in `action.yml` to include the words "dependency submission", the `gradle-build-action` now shows up in this search.

https://github.com/marketplace?type=actions&query=dependency+submission+gradle

**Comment by big-andy-coates** [comment]
Confirmed this shows up if I click the link from the dependencies tab :)
