### ISSUE TITLE
buildResultsRecorder - Permission Denied

### ISSUE THREAD

**Issue by sergeidyga** [gradle/gradle-build-action#866]
Build fails with Permission Denied
```
FAILURE: Build failed with an exception.

* Where:
Script '/home/gha-actions-runner/.gradle/init.d/gradle-build-action.build-result-capture-service.plugin.groovy' line: 58

* What went wrong:
Failed to stop service 'gradle-build-action-buildResultsRecorder'.
> /opt/actions-runner/_work/_temp/.build-results/__self-1693482877293.json (Permission denied)
```

ref to https://github.com/gradle/gradle-build-action/blob/8f08e41675472b8aa0aa2c356e8b2c1561af3bf9/src/resources/init-scripts/gradle-build-action.build-result-capture-service.plugin.groovy#L58C19-L58C19

**Comment by bigdaz** [comment]
Thanks for the report. Looks like the init script should be more tolerant of failures like this.

That said, it's odd that the action cannot write a file to the runner temp directory. Are you using self-hosted runners?

**Comment by sergeidyga** [comment]
thanks you for your response! yes, self-hosted
