### ISSUE TITLE
Doc clarification: When does Setup Gradle step not apply to subsequent executions?

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle-build-action#867]
Docs say:

> **Most** of the functionality of the gradle-build-action is applied via Gradle init-scripts, and so will apply to all subsequent Gradle executions on the runner, no matter how Gradle is invoked.

Emphasis on "most" is mine - when does this not apply?

I was about to switch to that method (a setup step, then using `run` action from then on) but wasn't sure if there might be a gotcha there to be aware of.

**Comment by bigdaz** [comment]
Yes, I can see how that could be confusing. In reality, all of the features apply regardless of how Gradle is invoked (via the `gradle-build-action` or via a `run` action).

So there's no practical difference between the 2 patterns, but we recommend specifying a `gradle-build-action` step to setup Gradle and then a simple `run` step to execute Gradle. This makes the use of the `gradle-build-action` less intrusive on your workflow.

I'll update the docs for clarity. Thanks for reporting.

**Comment by bigdaz** [comment]
I guess the "most" in that sentence applied to the use of init-scripts. Some functions (like setting the default version of Gradle) work by configuring environment variables that apply to all Steps in the Job.

**Comment by 3flex** [comment]
Thank you!
