### ISSUE TITLE
Documentation: Unclear how to publish a Build Scan with Gradle Enterprise injection or the `--scan` command-line

### ISSUE THREAD

**Issue by msgilligan** [gradle/gradle-build-action#870]
I want to use Gradle Enterprise injection on an Open Source (public) GitHub project to generate and publish a build scan. I do not want to use a key that I generated locally using a browser. The instructions say to log in to Gradle Enterprise, but I don't have a login and don't  see how to get one.

What am I missing? I think the documentation for this action (or the documentation for Build Scans) could be more clear.

**Comment by msgilligan** [comment]
Since creating this issue I've learned that I may not need Gradle Enterprise Plugin Injection to enable build scans, because I can just add `--scan` on the Gradle command line.  However, if I enable `--scan` on the command line _without_ installing the plugin, there is no way (in a CI environment) to agree to the terms of service.

**Comment by msgilligan** [comment]
I created this issue on Gradle itself: https://github.com/gradle/gradle/issues/26316

**Comment by bigdaz** [comment]
Thanks for the report. The GE injection functionality was designed for users who want to publish to self-hosted Gradle Enterprise instances, and not for publishing to scans.gradle.com.

But I can see the need for documentation on how to publish using `--scan`, since this almost always requires the acceptance of the Terms of Service, which in turn requires that the GE plugin be applied.

**Comment by msgilligan** [comment]
> The GE injection functionality was designed for users who want to publish to self-hosted Gradle Enterprise instances, and not for publishing to scans.gradle.com.

It would be helpful if the documentation said something to that effect.

> But I can see the need for documentation on how to publish using --scan, since this almost always requires the acceptance of the Terms of Service, which in turn requires that the GE plugin be applied.

Yes. Thank you!

**Comment by msgilligan** [comment]
Thanks @bigdaz !  Any chance you could bring https://github.com/gradle/gradle/issues/26316 to someone's attention?

**Comment by msgilligan** [comment]
@wolfs provided a great initialization script that works very well in a CI environment: https://github.com/gradle/gradle/issues/26316#issuecomment-1739245349

 (I've tested on GitHub Actions and GitLab CI)
