### ISSUE TITLE
configuration cache doesn't appear to be saved

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle-build-action#871]
at least from what [this line](https://github.com/xenoterracide/ai-wh40k/actions/runs/6114301274/job/16595581795#step:4:9), that otherwise had a cache hit told me

**Comment by bigdaz** [comment]
You're right. This functionality was disabled in [v2.4.2](https://github.com/gradle/gradle-build-action/releases/tag/v2.4.2).
The underlying reason is detailed in this vulnerability report: https://github.com/gradle/gradle-build-action/security/advisories/GHSA-h3qr-39j9-4r5v

**Comment by xenoterracide** [comment]
someone should report the vulnerability at github that secrets should never be stored in environment variables (the real vulnerability, their code)... urgh.
