### ISSUE TITLE
read/write/update cache options seem nonsensical and hard to understand in documentation

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle-build-action#872]
To get this set up correctly, I was trying to get it to work on a branch; of course, it didn't. So I set `cache-overwrite-existing: true`, which didn't fix the problem. Why? well, of course, it's because it's still set to be read-only. Imagine setting cache disabled, read-only, write-only, and only to true or false. What's that behavior? I could read the code to find out. This documentation is crazy, but arguably, so is the API. I shouldn't have to experiment on how to get the caches to update on a non-default branch (which is what it should be checking).

At least improve the documentation to define things that won't work if you do or don't do other things. Also, throw errors if mutually exclusive options are set.

**Comment by bigdaz** [comment]
Thanks for your feedback.
It would be even more helpful if you could suggest [some words that would make this clearer](https://github.com/gradle/gradle-build-action#using-the-cache-read-only).

The default cache behaviour was chosen to work for most users most of the time. Setting cache read-only all branches but `main` helps avoid cache churn.
