### ISSUE TITLE
After bumping from 2.7.0 to 2.8.0 `publish` produces duplicate staging repositories on oss sonar(maven)

### ISSUE THREAD

**Issue by osoykan** [gradle/gradle-build-action#875]
That's why I rolled back to 2.7.0, and it works now; there might be something with changes or my build scripts are slightly incompatible with the 2.8.0 🤔 

It's an open-source project here: https://github.com/Trendyol/stove4k

**Comment by bigdaz** [comment]
Can you link to the GitHub Actions run that resulted in duplicate staging repositories? This doesn't sound like something that the `gradle-build-action` would be responsible for, so I'd like to investigate.

**Comment by osoykan** [comment]
I didn't observe the same behavior in 2.9.0, hence closing; thanks!
