### ISSUE TITLE
Support job summary to be exported as step output

### ISSUE THREAD

**Issue by uwoobeat** [gradle/gradle-build-action#891]
Hello! I'm using `gradle-build-action` in my workflows and it has been incredibly helpful, especially for Job Summary feature.

Right now, the action allows us to post the Build Scan URL directly to the PR comments by referencing `steps.gradle.outputs.build-scan-url`. This is useful but limited to just the Build Scan URL.

It would be highly beneficial to expose the entire Job Summary as a step output. Something like `steps.gradle.outputs.job-summary` would be good. This could be similarly applied to the `github-script` for leaving a PR comment as you've introduced [here](https://github.com/gradle/gradle-build-action#build-scan-link-as-step-output).

Doing so would eliminate the need to tediously navigate to the GitHub Actions tab to check the job summary, allowing us instead to review the results directly in the PR comments, which would be very convenient.

**Comment by bigdaz** [comment]
Closing this issue, as it is superceded by #1020
