### ISSUE TITLE
Unexpected input: '}' @ line 62, column 1 within initialization script '/root/.gradle/init.d/gradle-build-action.github-dependency-graph.init.gradle'

### ISSUE THREAD

**Issue by mbroughton-aiwyn** [gradle/gradle-build-action#918]
gradle-build-action@v2

* Where:
Initialization script '/root/.gradle/init.d/gradle-build-action.github-dependency-graph.init.gradle' line: 62

* What went wrong:
Could not compile initialization script '/root/.gradle/init.d/gradle-build-action.github-dependency-graph.init.gradle'.
> startup failed:
  initialization script '/root/.gradle/init.d/gradle-build-action.github-dependency-graph.init.gradle': 62: Unexpected input: '}' @ line 62, column 1.
     }
     ^
  
  1 error

**Comment by bigdaz** [comment]
Thanks for the report. Are you still seeing this issue with the latest `gradle-build-action@v2`? If so, can you please provide some more details about your environment, including Gradle version. Any logs etc you can provide could be helpful.

**Comment by bigdaz** [comment]
Closing this as not reproducible
