### ISSUE TITLE
Node 16 Actions Deprecated

### ISSUE THREAD

**Issue by keith-h** [gradle/gradle-build-action#946]
Hi there,

I'm getting warnings like this on our actions pipelines:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3, gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
I've tried updating the gradle plugin to the latest commit release and still get the warning.  Is there a commit hash for a node 20-compatible version?

**Comment by bigdaz** [comment]
Thanks. I'll ensure that we bump the action to use Node 20 in an upcoming release.
