### ISSUE TITLE
[FEATURE REQUEST] custom cache name

### ISSUE THREAD

**Issue by dimaslanjaka** [gradle/gradle-build-action#947]
please add option cache name. prevent too many cache generated each commits, which currently github limiting cache sizes and total each repository.

**Comment by bigdaz** [comment]
I don't really understand what you're asking. Are you suggesting that a custom cache name could prevent caches growing too large?

There is a lot of information about caching documented here: https://github.com/gradle/gradle-build-action#caching-build-state-between-jobs

**Comment by dimaslanjaka** [comment]
> I don't really understand what you're asking. Are you suggesting that a custom cache name could prevent caches growing too large?
> 
> There is a lot of information about caching documented here: https://github.com/gradle/gradle-build-action#caching-build-state-between-jobs

cache name start with `v8` there too many caches with it. wait, ill re-run my previous ci to reproduce the caches. i was cleaned them and disabling `gradle-build-action` from my workflow yml config

**Comment by dimaslanjaka** [comment]
> I don't really understand what you're asking. Are you suggesting that a custom cache name could prevent caches growing too large?
> 
> There is a lot of information about caching documented here: https://github.com/gradle/gradle-build-action#caching-build-state-between-jobs

![image](https://github.com/gradle/gradle-build-action/assets/12471057/d4144fda-8599-494e-b5a8-ad65a78db224)

**Comment by dimaslanjaka** [comment]
add custom cache name to prevent duplicate caches each commit like this 
![image](https://github.com/gradle/gradle-build-action/assets/12471057/6baffe55-3bc1-495d-8cc9-ca06299e2eee)

**Comment by bigdaz** [comment]
Unfortunately that won't work. Each GitHub Actions cache entry is immutable, so we cannot use a fixed name and update the contents. Instead, each time the entry contents change, it is uploaded with a different name.

BUT, you'll notice that those "duplicated" entries are quite small. We extract common things like dependencies and wrapper zips so that they will be cached once and reused until the underlying contents change.

**Comment by dimaslanjaka** [comment]
now iam using `actions/cache` to solve gradle caching system https://github.com/dimaslanjaka/android-traffic-exchange/blob/a3ba8c74008206a404511b563b4dd482326345e0/.github/workflows/android.yml#L67-L75

then add jvm arg `--gradle-user-home` to `rootProject/.gradle` https://github.com/dimaslanjaka/android-traffic-exchange/blob/a3ba8c74008206a404511b563b4dd482326345e0/.github/workflows/android.yml#L107-L118

The result all downloaded jars, build cache, etc in `rootProject/.gradle`

and the build with cache task working like charm

![image](https://github.com/gradle/gradle-build-action/assets/12471057/5deb96a8-a5e0-44ab-840f-4a510b205e1d)

**Comment by bigdaz** [comment]
> now iam using actions/cache to solve gradle caching system https://github.com/dimaslanjaka/android-traffic-exchange/blob/a3ba8c74008206a404511b563b4dd482326345e0/.github/workflows/android.yml#L57-L75

You are using a fixed cache key. From my understanding the cache entry for this key will be written ONCE ONLY and will never be updated. So over time this cache entry will be become more and more out of date, and less useful.

From the [cache documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action):
> You cannot change the contents of an existing cache. Instead, you can create a new cache with a new key.

**Comment by dimaslanjaka** [comment]
> > now iam using actions/cache to solve gradle caching system https://github.com/dimaslanjaka/android-traffic-exchange/blob/a3ba8c74008206a404511b563b4dd482326345e0/.github/workflows/android.yml#L57-L75
> 
> You are using a fixed cache key. From my understanding the cache entry for this key will be written ONCE ONLY and will never be updated. So over time this cache entry will be become more and more out of date, and less useful.
> 
> From the [cache documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action):
> 
> > You cannot change the contents of an existing cache. Instead, you can create a new cache with a new key.

yeah but not created new caches every push. it will make my github account experience limited github actions because the total cache exceeds the 10GB limit.
