### ISSUE TITLE
Add support for configuration cache state storing

### ISSUE THREAD

**Issue by krzema12** [gradle/gradle-build-action#966]
See https://docs.gradle.org/current/userguide/configuration_cache.html
Currently the state of the cache is not stored by this action.

**Comment by JavierSegoviaCordoba** [comment]
This should be possible as https://github.com/gradle/gradle/pull/27174 is merged

**Comment by nuhkoca** [comment]
@JavierSegoviaCordoba it is merged. Does this action need to do anything more or configuration cache should be supported out of the box?

**Comment by JavierSegoviaCordoba** [comment]
Config cache code needs to be restored and changed a bit in this action.

**Comment by bigdaz** [comment]
This functionality has been implemented and is pre-released as [`v3.0.0-beta.1`](https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0-beta.1).
To follow the latest pre-release version in the 3.x line, you can use `gradle/gradle-build-action@v3-prerelease`.
