### ISSUE TITLE
Cache miss on macOS and Windows

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#988]
I am triggering a matrix with the three OS. Calling it two times in a row with a `workflow_dispatch` should avoid rerunning all cacheable tasks in the second run, but this is only happening on Ubuntu.

- Run: https://github.com/JavierSegoviaCordoba/detekt-rules/actions/runs/7119436063
  - Ubuntu time: 52s
  - macOS time: 3m 32s
  - Windows time: 2m 19s
- Gradle Scans
  - Ubuntu: https://scans.gradle.com/s/7pzuyv5jdnjfi/performance/execution
  - macOS: https://scans.gradle.com/s/id7s5v5h7h3to/performance/execution
  - Windows: https://scans.gradle.com/s/3butjrhvrd2ts/performance/execution
  
  
Looks like there are some issues with the action related to the accessors (it shows Gradle 8.4, but the project is using Gradle 8.5).

```
Unhandled error in Gradle post-action - job will continue: Error: ENOENT: no such file or directory, realpath 'C:\Users\runneradmin\.gradle\caches\8.4\kotlin-dsl\accessors\2cef9241056ff6787ec530b1dbb398f1\classes\org\gradle\kotlin\dsl'
```

**Comment by bigdaz** [comment]
Thanks for the report @JavierSegoviaCordoba. The "Unhandled error" is very likely to be the problem, and this appears to be coming from the `cache-cleanup` part of the action. 
This problem during cache cleanup seems to be causing the rest of the post-action to abort, including writing the job summary. (Which means we can't see [a caching summary like this](https://github.com/JavierSegoviaCordoba/detekt-rules/actions/runs/7119436063#summary-19384527318) for the MacOS/Windows run).

I suspect that you may have seen a similar issue with the build that should have written the data to the cache, but I'm unable to find that CI run. Can you repeat your experiment after deleting any GitHub Actions cache entries and share the links to both GitHub Actions runs (the one that writes the entries to cache and the one that should read them back).

In any case, the action should be more robust with respect to failures during cache-cleanup.

**Comment by JavierSegoviaCordoba** [comment]
I confirm it works. But I had to manually delete 30 cache files one by one via GitHub UI 😅

**Comment by bigdaz** [comment]
Closing this in preference of #990
